### ISSUE TITLE
No.8 Categories一覧 紐づき商品の確認

### ISSUE THREAD

**Issue by Ta9m1-N** [Ta9m1-N/bugslife_java-1.0.1#17]
## 概要
一覧画面の？を押下するとカテゴリーに紐づく商品を確認できるように修正。
## 不具合調査結果
category-index.jsの記述が原因でコンソールエラーが発生している。
## 修正方針
$(document).loadを$(document).readyに変更する。
### View(HTML,JS)

- [x] category-index.jsの修正

### Issue 情報更新

- [x] 回答までのアプローチ
- [x] プロンプト履歴

- [x] PullRequest の紐付け

**Comment by Ta9m1-N** [comment]
### 回答までのアプローチ
商品データが無かったため、商品データを登録できるようにcategory-product.jsのpostDataの値を変更(JSON形式として認識させるため)。
プロンプトの回答からコンソールエラーの原因を特定、修正。
### プロンプト履歴
商品データの登録時　https://chat.openai.com/share/75da3658-d2fa-4390-9c21-acb9abb28746
コンソールエラーの原因特定、修正方法
User
$(document).load(function () {
  var tooltipTriggerList = [].slice.call(
    document.querySelectorAll('[data-bs-toggle="tooltip"]')
  );
  var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
    return new bootstrap.Tooltip(tooltipTriggerEl, {
      trigger: "click",
    });
  });
});
クリックしても表示されない
日本語で

ChatGPT
あなたのコードは、BootstrapのTooltipを使ってクリック時に表示するように設定されています。ただし、$(document).load は正確なイベント名ではないため、期待通りに動作しない可能性があります。

代わりに、$(document).ready イベントを使用してみてください。以下は修正されたコードの例です。

```
$(document).ready(function () {
  var tooltipTriggerList = [].slice.call(
    document.querySelectorAll('[data-bs-toggle="tooltip"]')
  );
  var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
    return new bootstrap.Tooltip(tooltipTriggerEl, {
      trigger: "click",
    });
  });
});
```
これで、ページの読み込みが完了したときにコードが実行され、クリック時にTooltipが表示されるはずです。また、もしまだ表示されない場合は、デバッグツールを使用してコンソールエラーを確認し、それに対処することもお勧めします。

User
jquery-3.7.0.min.js:2 Uncaught TypeError: e.indexOf is not a function
    at ce.fn.load (jquery-3.7.0.min.js:2:82803)
    at category-index.js:1:13
コンソールエラー

ChatGPT
エラーメッセージから見て取れるとおり、問題はce.fn.loadメソッドで発生しています。これはloadメソッドの使用に関連しています。

一般的に、loadメソッドは、関数を引数として受け取ることが期待されています。しかし、エラーメッセージからは、e.indexOfのような文字列に対してindexOfを呼び出そうとしているように見えます。これは通常、loadメソッドに渡される関数が期待通りではない場合に発生します。

修正するために、次のようなアプローチを検討してみてください。以下は修正されたコードの例です。

```
$(document).ready(function () {
  var tooltipTriggerList = [].slice.call(
    document.querySelectorAll('[data-bs-toggle="tooltip"]')
  );
  var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
    return new bootstrap.Tooltip(tooltipTriggerEl, {
      trigger: "click",
    });
  });
});
```
また、jQueryのloadメソッドは非推奨となっており、代わりにonメソッドを使用することが推奨されています。以下はその例です。

```
$(document).ready(function () {
  var tooltipTriggerList = [].slice.call(
    document.querySelectorAll('[data-bs-toggle="tooltip"]')
  );
  var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
    return new bootstrap.Tooltip(tooltipTriggerEl, {
      trigger: "click",
    });
  });
});
```
この変更で問題が解決するかどうかを確認してください。それでもエラーが続く場合は、他のコードやプラグインが影響している可能性も考えられます。
